# NumPy

## Understanding Data Types in Python


```C
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

While in Python the equivalent operation could be written this way:
```python
# Python code
result = 0
for i in range(100):
    result += i
```


```C
/* C code */
int x = 4;
x = "four";  // FAILS
```

Python spremenljivka dobi zraven veliko informacij, zato je dosti večja kot npr. v C.

### A Python Integer Is More Than Just an Integer

```C
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

A single integer in Python 3.4 actually contains four pieces:
- ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation
- ob_type, which encodes the type of the variable
- ob_size, which specifies the size of the following data members
- ob_digit, which contains the actual integer value that we expect the Python variable to represent.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/cint_vs_pyint.png" alt="Integer Memory Layout">

### A Python List Is More Than Just a List


In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [5]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

Tudi, če vemo, da bodo v seznamu samo intigerji, python za vsakega napiše vse informacije. Numpy pa reši to situacijo. Samo za en element določi lastnosti, kar zmanjša velikost podatkov. Zato je hitrejši. Je pa omejitev, da lahko v en seznam lahko shranimo samo en tip objekta.


<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png" alt="Array Memory Layout">

### Fixed-Type Arrays in Python


In [7]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To zgoraj je malo v smeri numpya (brez numpya)...

## How Vectorization Makes Code Faster



<p><img alt="Translating Python code to bytecode" src="https://s3.amazonaws.com/dq-content/289/bytecode.svg"></p>


<table>
<thead>
<tr>
<th>Language Type</th>
<th>Example</th>
<th>Time taken to write program</th>
<th>Control over program performance</th>
</tr>
</thead>
<tbody>
<tr>
<td>High-Level</td>
<td>Python</td>
<td>Low</td>
<td>Low</td>
</tr>
<tr>
<td>Low-Level</td>
<td>C</td>
<td>High</td>
<td>High</td>
</tr>
</tbody>
</table>



<p><img alt="For loop to sum rows" src="https://s3.amazonaws.com/dq-content/289/for_loop.svg"></p>

Numpy združi najboljše od python sintakse in C optimizacije hitrosti. To dosežemo z vektorizacijo.

To spodaj je python osnovna sintaksa:

In [8]:
my_numbers = [[6,5],[1,3],[5,6]]
sums = []
for row in my_numbers:
    row_sum = row[0]+row[1]
    sums.append(row_sum)
print(sums)

[11, 4, 11]



<p><img alt="Unvectorized operation" src="https://s3.amazonaws.com/dq-content/289/unvectorized.svg"></p>

Pri vektorizaciji naredimo obe operaciji istočasno - SIMD. Ne seštevamo vrstico po vrstico, ampak združimo več ciklov v enega.

<p><img alt="Vectorized operation" src="https://s3.amazonaws.com/dq-content/289/vectorized.svg"></p>



## Numpy = numerical Python

Tudi Pandas temelji na Numpy-u. Algoritmi so 10x-100x hitrejši kot v Pythonu. Ima zelo dobro knjižnico, help, ... 

ndarray - omogoča hitre aritmetične operacije

In [10]:
#uvozimo knjiznico
import numpy as np

### NumPy ndarrays

Večdimenzionalni seznami.



<p><img alt="Dimensional Arrays" src="https://s3.amazonaws.com/dq-content/289/dimensional_arrays.svg"></p>



#### Create an array



In [16]:
#da naredimo array, uporabimo funkcijo array
list1 = [4,5,6,78,12]
#seznam spremenimo v numpy array
arr1 = np.array(list1)
print(arr1)
#če damo vmes nek element kot float, naredi vse elemente tega tipa
type(arr1)

[ 4  5  6 78 12]


numpy.ndarray

In [18]:
data2 = [[1.1,2,3],[3,2,11]]
arr2 = np.array(data2)
print(arr2)

[[ 1.1  2.   3. ]
 [ 3.   2.  11. ]]


### Funkcije za ustvarjanje pogostih arrayev

In [19]:
#ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
#arange (podobna funkciji range v Pythonu), (od, do, korak)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
#zeros
Aa=np.zeros((3,5))
Bb=np.zeros((5))
print(Aa, '\n')
print(Bb)

Aa=[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[0. 0. 0. 0. 0.]


In [30]:
#linspace (interval od, interval do, na koliko delov razdelimo)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
#randint (števila od, števila do,(velikost matrike))
np.random.randint(0,10,(4,4))

array([[7, 2, 9, 2],
       [5, 1, 0, 7],
       [3, 7, 9, 8],
       [4, 5, 0, 3]])

In [38]:
#random (najključna števila med 0 in 1, (velikost matrike))
np.random.random((3,3))

array([[0.3480086 , 0.49263108, 0.21096055],
       [0.54280082, 0.73469633, 0.89570865],
       [0.91811405, 0.04376255, 0.55394838]])

In [40]:
#eye (kvadratna matrika z enkami po diagonali)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
#full (matrika velikosti (m,n) s konstantno vrednostjo)
np.full((5,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [48]:
#empty (naredi prazen array???) preveri zakaj ni prazen???
np.empty((2,1))

array([[-5.73021895e-300],
       [ 1.06098609e-153]])

#### Understanding NumPy ndarrays

In [50]:
data3 = np.random.randint(0,10,(4,7))
data3

array([[4, 8, 5, 0, 5, 3, 3],
       [9, 9, 2, 5, 4, 9, 1],
       [8, 7, 6, 1, 6, 0, 7],
       [9, 4, 3, 8, 6, 4, 7]])

In [51]:
#ndim - število dimenzij ndarraya
data3.ndim

2

In [53]:
#shape - velikost matrike (št vrstic, št stolpcev), dimenzija (ta primer 2D)
data3.shape

(4, 7)

In [56]:
#size - število elementov (če je več D, vrne pač število vseh elementov)
data3.size

28

In [58]:
#itemsize - velikost enega elementa v arrayu (v bajtih)
data3.itemsize

8

In [60]:
#nbytes - velikost celega arraya (v bajtih)
data3.nbytes

224

#### Selecting and Slicing Rows and Items from ndarrays

<p><img alt="Selecting rows from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_rows.svg"></p>



This is how we select a single item from a 2D ndarray:

<p><img alt="Selecting a single item from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_item.svg"></p>


ndarray[row, column] - tukaj je edina razlika s pythonovim listom [][]

Možnosti za izbiranje elementov
- int 5
- slice 0:5, 5
- :
- [1,5,8]
- boolean array

### Vrstice

In [63]:
test_arr = np.random.randint(10,size=(5,5))
test_arr

array([[2, 3, 1, 4, 0],
       [4, 7, 7, 7, 3],
       [3, 7, 2, 1, 1],
       [1, 5, 1, 3, 3],
       [2, 5, 1, 8, 3]])

In [68]:
#prva vrstica
first_row = test_arr[0]
first_row

array([2, 3, 1, 4, 0])

In [71]:
#2. in 3. vrstica
row2_3 = test_arr[[1,2]] #ali row2_3 = [1:3]
row2_3

array([[4, 7, 7, 7, 3],
       [3, 7, 2, 1, 1]])

In [73]:
#vrstica 2 do konca
row2_do_konca = test_arr[1:]
row2_do_konca

array([[4, 7, 7, 7, 3],
       [3, 7, 2, 1, 1],
       [1, 5, 1, 3, 3],
       [2, 5, 1, 8, 3]])

#### Selecting Columns and Custom Slicing ndarrays

Let's continue by learning how to select one or more columns of data:

<p><img alt="Selecting columns from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_columns.svg"></p>



If we wanted to select a partial 1D slice of a row or column, we can combine a single value for one dimension with a slice for the other dimension:

<p><img alt="Selecting partial 1D slices from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_1darray.svg"></p>

Lastly, if we wanted to select a 2D slice, we can use slices for both dimensions:

<p><img alt="Selecting a 2D slice from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_2darray.svg"></p>



### Stolpci

`[vrstice, stolpci]`

In [74]:
test_arr2 = np.random.randint(10,size=(5,5))
test_arr2

array([[6, 3, 3, 3, 2],
       [4, 8, 7, 2, 6],
       [7, 6, 3, 1, 3],
       [4, 2, 4, 0, 8],
       [6, 3, 4, 5, 8]])

In [77]:
#stolpec 2
stolp2 = test_arr2[:,1]
print(stolp2)

[3 8 6 2 3]


In [79]:
#stolpec 1 in 2
stolp1_2 = test_arr2[:,0:2] #ali =test_arr2[:,:2]
stolp1_2

array([[6, 3],
       [4, 8],
       [7, 6],
       [4, 2],
       [6, 3]])

In [81]:
#stolpec 2,4,5
stolp2_4_5 = test_arr2[:,[1,3,4]]
stolp2_4_5

array([[3, 3, 2],
       [8, 2, 6],
       [6, 1, 3],
       [2, 0, 8],
       [3, 5, 8]])

In [85]:
#stolpec elementi 2 do 4, vrstica 3
stolp_vrstica = test_arr2[2, 1:4]
stolp_vrstica

array([6, 3, 1])

In [87]:
#elementi v vrsticah 1-4, stolpce 1-3
test_arr2[1:4,:3]

array([[4, 8, 7],
       [7, 6, 3],
       [4, 2, 4]])

#### Modify values in ndarray



In [88]:
test_arr2

array([[6, 3, 3, 3, 2],
       [4, 8, 7, 2, 6],
       [7, 6, 3, 1, 3],
       [4, 2, 4, 0, 8],
       [6, 3, 4, 5, 8]])

In [93]:
test_arr2[0,0] = 124
test_arr2
#POZOR:če bi v seznam zdaj dodali float, bi decimalko odrezal, ker je nastavljen na intiger!

array([[124,   3,   3,   3,   2],
       [  4,   8,   7,   2,   6],
       [  7,   6,   3,   1,   3],
       [  4,   2,   4,   0,   8],
       [  6,   3,   4,   5,   8]])

#### Datatypes

[Več o datatypes](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)

[List of scalars](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html#arrays-scalars-built-in)

8 bajtni intiger zajema številke od 0 do 255 (če recimo v nekem arrayu uporabljamo samo ta števila, je smiselno nastaviti tako, na 8 bajtov)

In [95]:
#pogledamo tip seznama
x=np.array([1,2])
print(x.dtype)

int64


In [98]:
#nastavljanje tipa podatkov
np.zeros(10, dtype=np.int16) #ali np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

<div class="text_cell_render border-box-sizing rendered_html">
<table>
<thead><tr>
<th>Data type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>bool_</code></td>
<td>Boolean (True or False) stored as a byte</td>
</tr>
<tr>
<td><code>int_</code></td>
<td>Default integer type (same as C <code>long</code>; normally either <code>int64</code> or <code>int32</code>)</td>
</tr>
<tr>
<td><code>intc</code></td>
<td>Identical to C <code>int</code> (normally <code>int32</code> or <code>int64</code>)</td>
</tr>
<tr>
<td><code>intp</code></td>
<td>Integer used for indexing (same as C <code>ssize_t</code>; normally either <code>int32</code> or <code>int64</code>)</td>
</tr>
<tr>
<td><code>int8</code></td>
<td>Byte (-128 to 127)</td>
</tr>
<tr>
<td><code>int16</code></td>
<td>Integer (-32768 to 32767)</td>
</tr>
<tr>
<td><code>int32</code></td>
<td>Integer (-2147483648 to 2147483647)</td>
</tr>
<tr>
<td><code>int64</code></td>
<td>Integer (-9223372036854775808 to 9223372036854775807)</td>
</tr>
<tr>
<td><code>uint8</code></td>
<td>Unsigned integer (0 to 255)</td>
</tr>
<tr>
<td><code>uint16</code></td>
<td>Unsigned integer (0 to 65535)</td>
</tr>
<tr>
<td><code>uint32</code></td>
<td>Unsigned integer (0 to 4294967295)</td>
</tr>
<tr>
<td><code>uint64</code></td>
<td>Unsigned integer (0 to 18446744073709551615)</td>
</tr>
<tr>
<td><code>float_</code></td>
<td>Shorthand for <code>float64</code>.</td>
</tr>
<tr>
<td><code>float16</code></td>
<td>Half precision float: sign bit, 5 bits exponent, 10 bits mantissa</td>
</tr>
<tr>
<td><code>float32</code></td>
<td>Single precision float: sign bit, 8 bits exponent, 23 bits mantissa</td>
</tr>
<tr>
<td><code>float64</code></td>
<td>Double precision float: sign bit, 11 bits exponent, 52 bits mantissa</td>
</tr>
<tr>
<td><code>complex_</code></td>
<td>Shorthand for <code>complex128</code>.</td>
</tr>
<tr>
<td><code>complex64</code></td>
<td>Complex number, represented by two 32-bit floats</td>
</tr>
<tr>
<td><code>complex128</code></td>
<td>Complex number, represented by two 64-bit floats</td>
</tr>
</tbody>
</table>

</div>

### Computation on NumPy Arrays: Universal Functions


#### The Slowness of Loops



Numpy knjižnica ima hitrostno računanje že implementirano.

In [5]:
import numpy as np

#### Python način generiranja funkcije (počasen)

In [8]:
#python način generiranja funkcije
def comute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [9]:
np.random.seed(0) #povsod generira iste random vrednosti (preveri še doma)
values = np.random.randint(1,10,size=5)
comute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [10]:
big_array = np.random.randint(1,100,size=1000000)

In [11]:
%timeit comute_reciprocals(big_array)

5 s ± 147 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### Numpy način zapisa funkcije (hitrejši)

In [13]:
l1 = [1,2,3]
l2 = [4,5,6]
#sešteti želimo prvi element iz l1 s prvim iz l2, drugi iz l1 z drigim iz l2, ...

In [14]:
print(comute_reciprocals(values))

[0.16666667 1.         0.25       0.25       0.125     ]


In [16]:
print(1/values) #zaradi vektorizacije ne potrebujemo for zanke

[0.16666667 1.         0.25       0.25       0.125     ]


In [17]:
%timeit (1.0/big_array) #dosti hitreje kot for zanka

1.52 ms ± 71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [21]:
#računamo lahko tudi z večdimenzijskimi arrayi
x = np.arange(9).reshape((3,3)) #reshape preoblikuje npr. v matriko 3x3

In [22]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### Uvoz realnih podatkov


In [26]:
!head taxi_data.csv #linux ukaz

In [27]:
import csv

In [28]:
with open('taxi_data.csv', 'r') as f:
    taxi_list = list(csv.reader(f))

In [33]:
taxi_list = taxi_list[2:] #odrežemo prvi dve vrstici.
#vse številke so še kot stringi, imamo še navaden python list, ki ga moramo še pretvoriti
#v numpy array

In [37]:
#pretvorimo v numpy array
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        try:
            converted_row.append(float(item))
        except:
            continue
    converted_taxi_list.append(converted_row)
#zdaj, ko ima naš list vse iste vrednosti (float), ga lahko spremenimo v numpy array

In [38]:
taxi = np.array(converted_taxi_list)

- Row 1 is RatecodeID
- Row 2 is PULocationID
- Row 3 is DOLocationID
- Row 4 is passenger_count
- Row 5 is trip_distance
- Row 6 is fare_amount
- Row 7 is extra
- Row 8 is mta_tax
- Row 9 is tip_amount
- Row 10 is tolls_amount
- Row 11 is improvement_surcharge
- Row 12 is total_amount
- Row 13 is payment_type
- Row 14 is trip_type

### Vector Math



In [40]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x+y

array([5, 7, 9])

In [41]:
x**2

array([1, 4, 9])

In [42]:
#skalarni produkt
x.dot(y)

32

In [44]:
z = np.array([x, y**2])
z

array([[ 1,  2,  3],
       [16, 25, 36]])

In [46]:
#transponiramo
a = z.T
a

array([[ 1, 16],
       [ 2, 25],
       [ 3, 36]])

In [48]:
col1 = taxi[:,6]
col2 = taxi[:,8]
col3 = taxi[:,11]

In [49]:
sums = col1+col2+col3

In [50]:
#arrayi morajo imeti iste dimenzije (seštevanje, ...)


Here's what happened behind the scenes:

<p><img alt="Vectorized Addition" src="https://s3.amazonaws.com/dq-content/289/vectorized_addition.svg"></p>


- `vector_a + vector_b` - Addition
- `vector_a - vector_b7` - Subtraction
- `vector_a * vector_b` - Multiplication (this is unrelated to the vector multiplication used in linear algebra).
- `vector_a / vector_b` - Division
- `vector_a % vector_b` - Modulus (find the remainder when vector_a is divided by vector_b)
- `vector_a ** vector_b` - Exponent (raise vector_a to the power of vector_b)
- `vector_a // vector_b` - Floor Division (divide vector_a by vector_b, rounding down to the nearest integer)

In [51]:
taxi.shape

(19996, 15)

In [52]:
#izračunamo povprečno porabo
trip_distance = taxi[:,5]
trip_price = taxi[:,12]
price_per_mile = trip_price/trip_distance

/home/luka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
/home/luka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [53]:
price_per_mile

array([4.62608696, 5.59241706, 4.63768116, ..., 3.70046083, 4.11904762,
       5.12      ])

In [55]:
#spodnja funkcija naredi enako kot funkcija zgorag
price_per_mile2 = np.divide(trip_price,trip_distance)

/home/luka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/home/luka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  



<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>The following table lists the arithmetic operators implemented in NumPy:</p>
<table>
<thead><tr>
<th>Operator</th>
<th>Equivalent ufunc</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>+</code></td>
<td><code>np.add</code></td>
<td>Addition (e.g., <code>1 + 1 = 2</code>)</td>
</tr>
<tr>
<td><code>-</code></td>
<td><code>np.subtract</code></td>
<td>Subtraction (e.g., <code>3 - 2 = 1</code>)</td>
</tr>
<tr>
<td><code>-</code></td>
<td><code>np.negative</code></td>
<td>Unary negation (e.g., <code>-2</code>)</td>
</tr>
<tr>
<td><code>*</code></td>
<td><code>np.multiply</code></td>
<td>Multiplication (e.g., <code>2 * 3 = 6</code>)</td>
</tr>
<tr>
<td><code>/</code></td>
<td><code>np.divide</code></td>
<td>Division (e.g., <code>3 / 2 = 1.5</code>)</td>
</tr>
<tr>
<td><code>//</code></td>
<td><code>np.floor_divide</code></td>
<td>Floor division (e.g., <code>3 // 2 = 1</code>)</td>
</tr>
<tr>
<td><code>**</code></td>
<td><code>np.power</code></td>
<td>Exponentiation (e.g., <code>2 ** 3 = 8</code>)</td>
</tr>
<tr>
<td><code>%</code></td>
<td><code>np.mod</code></td>
<td>Modulus/remainder (e.g., <code>9 % 4 = 1</code>)</td>
</tr>
</tbody>
</table>
<p>Additionally there are Boolean/bitwise operators; we will explore these in <a href="02.06-boolean-arrays-and-masks.html">Comparisons, Masks, and Boolean Logic</a>.</p>

</div>
</div>

[Mathematical expressions](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.math.html#arithmetic-operations)

### Calculating Statistics For 1D ndarrays



In [57]:
price_min = taxi[:,12].min()
price_max = taxi[:,12].max()
price_min

-60.0

In [58]:
#funkcija
np.max(taxi[:,12])
#metoda
taxi[:,12].max()

240.0

### Calculating Statistics For 2D ndarrays

For now, we're going to look at how we can calculate statistics for two-dimensional ndarrays. If we use the arrays without additional parameters, they will return a single value, just like they do with a 1D array:

<p><img alt="Array method without axis parameter" src="https://s3.amazonaws.com/dq-content/289/array_method_axis_none.svg"></p>

But what if we wanted to find the maximum value of each row? For that, we need to use the axis parameter, and specify a value of 1, which indicates we want to calculate values for each row.

<p><img alt="Array method without axis 1" src="https://s3.amazonaws.com/dq-content/289/array_method_axis_1.svg"></p>

If we want to find the maximum value of each column, we use an axis value of 0:

<p><img alt="Array method without axis 1" src="https://s3.amazonaws.com/dq-content/289/array_method_axis_0.svg"></p>

To help you remember which is which, you can think of the first axis as rows, and the second axis as columns, just in the same way as when we're indexing a 2D NumPy array we use ndarray[row,column]. Then you think about which axis you want to apply the method along. The tricky part is to remember that when you apply the method along one axis, you get results in the other axis. Here is an illustration of that:

<p><img alt="The axis parameter" src="https://s3.amazonaws.com/dq-content/289/axis_param.svg"></p>



In [62]:
taxi_first20_rows = taxi[:20]

In [63]:
cene_skupaj = taxi_first20_rows[:,6:12]

In [64]:
cene_skupaj_preracunano = taxi_first20_rows[:,12] #že preračunana vsota v datasetu

In [65]:
cena_sestevek = cene_skupaj.sum(axis=1) #enako seštejemo še sami

In [66]:
print(cene_skupaj_preracunano, cena_sestevek) #dobimo isto

[15.96 11.8  12.8  16.3  20.3  12.3   6.3  14.8  11.76 23.3  31.3   8.3
 25.74 11.3   3.   12.36 21.59 11.8  27.36 11.8 ] [15.96 11.8  12.8  16.3  20.3  12.3   6.3  14.8  11.76 23.3  31.3   8.3
 25.74 11.3   3.   12.36 21.59 11.8  27.36 11.8 ]


In [67]:
cene_skupaj_preracunano.round()

array([16., 12., 13., 16., 20., 12.,  6., 15., 12., 23., 31.,  8., 26.,
       11.,  3., 12., 22., 12., 27., 12.])

In [68]:
cene_skupaj_preracunano.round(2)

array([15.96, 11.8 , 12.8 , 16.3 , 20.3 , 12.3 ,  6.3 , 14.8 , 11.76,
       23.3 , 31.3 ,  8.3 , 25.74, 11.3 ,  3.  , 12.36, 21.59, 11.8 ,
       27.36, 11.8 ])

### Adding Rows and Columns to ndarrays


In [69]:
ones = np.ones((2,3))

In [70]:
zeros = np.zeros(3)

In [73]:
combined = np.concatenate([ones, zeros], axis=0) #to ne dela, ker zeros.shape=(3,), ones.shape=(2,3)
#imamo 2D in 1D objekt, kar ne gre skupaj

ValueError: all the input arrays must have same number of dimensions

In [75]:
#lahko uporabimo funkcijo reshape ali zeros_2D=np.zeros(1,3)
zeros_2D = np.expand_dims(zeros, axis=0)

In [78]:
combined_2D = np.concatenate([ones, zeros_2D], axis=0)
#če želimo dodati stolpec, damo axis=1

In [77]:
combined_2D

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [79]:
price_per_mile.shape

(19996,)

In [80]:
price_per_mile_2D = np.expand_dims(price_per_mile, axis=1)

In [81]:
price_per_mile_2D.shape

(19996, 1)

In [83]:
#dodamo stolpec
taxi_data = np.concatenate([taxi,price_per_mile_2D], axis=1)

### Sorting ndarrays


In [85]:
sadje = np.array(['pomaranca', 'jabolko', 'kivi', 'mango', 'cesnja'])

In [87]:
sadje[[2,1]] #iščemo po indeksih

array(['kivi', 'jabolko'], dtype='<U9')

In [90]:
sorted_order = np.argsort(sadje)

In [91]:
sorted_order #razvrsti indekse objektov

array([4, 1, 2, 3, 0])

In [95]:
sortirano_sadje = sadje[sorted_order]
sortirano_sadje

array(['cesnja', 'jabolko', 'kivi', 'mango', 'pomaranca'], dtype='<U9')

#### Razvrščanje 2D arrayev

In [96]:
int_square = np.random.randint(10, size=(5,5))

In [100]:
#želimo, da v zgornjem arrayu pogledamo zadnji stolpec in vrstice razvrstimo glede 
#na naraščajoče vrednosti v zadnjem stolpcu
last_column = int_square[:,4]
sorted_order_matrika = np.argsort(last_column)
last_column_sorted = last_column[sorted_order_matrika]
int_square_sorted = int_square[sorted_order_matrika]
int_square_sorted
#lahko pa tudi združimo vse v eno vrstico ...

array([[6, 7, 0, 3, 2],
       [0, 0, 3, 3, 4],
       [8, 6, 5, 5, 6],
       [7, 9, 7, 6, 8],
       [2, 5, 3, 1, 9]])

In [102]:
#primer na taxi podatkih
sorted_order_taxi = np.argsort(taxi_data[:,-1])
taxi_sorted = taxi_data[sorted_order_taxi]
taxi_sorted[:20,-1]

array([         -inf,          -inf,          -inf,          -inf,
                -inf,          -inf,          -inf,          -inf,
                -inf,          -inf,          -inf, -693.33333333,
       -380.        , -380.        , -380.        , -192.5       ,
       -190.        , -138.94736842, -126.66666667,  -95.        ])

###  Reading CSV files with NumPy

In [103]:
taxi_np = np.genfromtxt('taxi_data.csv',
                       delimiter=',',
                       skip_header=2)

In [107]:
taxi_np #prebere tudi stolpce, ki so sicer stringi, ampak jih zapiše kot nan

array([[ 2.  ,   nan,   nan, ...,  9.8 ,  2.  ,  1.  ],
       [ 2.  ,   nan,   nan, ...,  7.8 ,  2.  ,  1.  ],
       [ 2.  ,   nan,   nan, ..., 15.96,  1.  ,  1.  ],
       ...,
       [ 1.  ,   nan,   nan, ..., 80.3 ,  1.  ,  1.  ],
       [ 1.  ,   nan,   nan, ..., 17.3 ,  1.  ,  1.  ],
       [ 1.  ,   nan,   nan, ..., 12.8 ,  1.  ,  1.  ]])

In [106]:
taxi_np.shape

(19998, 19)

###  Boolean Arrays





Še en način za izbiranje elementov v arrajih

In [108]:
np.array([2,3,6,7,9,23]) < 5

array([ True,  True, False, False, False, False])

A similar pattern occurs– the 'less than five' operation is applied to each value in the array. The diagram below shows this step by step:

<p><img alt="Vectorized boolean operation" src="https://s3.amazonaws.com/dq-content/290/vectorized_bool.svg"></p>

In [109]:
a = np.array([1,2,3,4,6])
a_bool = a < 3
a_bool

array([ True,  True, False, False, False])

In [110]:
b = np.array(['r','h', 'k'])
b_bool = b == 'r'
b_bool

array([ True, False, False])

### Boolean Indexing with 1D ndarrays




<p><img alt="Boolean indexing 1D ndarrays 1" src="https://s3.amazonaws.com/dq-content/290/1d_bool_1.svg"></p>



<p><img alt="Boolean indexing 1D ndarrays 2" src="https://s3.amazonaws.com/dq-content/290/1d_bool_2.svg"></p>




In [112]:
passenger_count = taxi_np[:,7]
two_passenger_bool = passenger_count == 2
two_passenger = passenger_count[two_passenger_bool]
two_passenger

array([2., 2., 2., ..., 2., 2., 2.])

### Boolean Indexing with 2D ndarrays


<p><img alt="Boolean indexing 1D ndarrays 2" src="https://s3.amazonaws.com/dq-content/290/bool_dims.svg"></p>


In [114]:
arr = np.random.randint(10,size=(4,3))
bool_ena = [True, False, True]
arr[:,bool_ena]

array([[1, 9],
       [2, 1],
       [1, 8],
       [9, 9]])

### Assigning Values in ndarrays

In [116]:
barve = ['blue','red','orange']
barve[1] = 'black'
barve

['blue', 'black', 'orange']

In [121]:
barve[1:] = 'pink'

In [122]:
barve

['blue', 'p', 'i', 'n', 'k']

### Subarrays as no-copy views



In [123]:
r = np.ones((4,4))
r2 = r[:2,:2]
r2

array([[1., 1.],
       [1., 1.]])

In [124]:
r2 [:] = 0

In [126]:
r #ko spremenimo r2, se spremeni tudi r !!!

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Copying Data


In [127]:
r3 = np.random.randint(10,size=(5,5))
r3_sub_copy = r3[:2,:2].copy()

In [129]:
r3_sub_copy #to je zdaj kopija in ne bo spremenila r3, če jo spremenimo

array([[6, 5],
       [0, 7]])